all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
hello:
	java -classpath "../.." s4.B193349/Hello
Frequencer:
	java -classpath "../.." s4.B193349/Frequencer
InformationEstimator:
	java -classpath "../.." s4.B193349/InformationEstimator
TestCase:
	java -classpath "../.." s4.B193349/TestCase
